query getPageBlogPost($locale: String, $preview: Boolean, $slug: String) {
  pageBlogPostCollection(locale: $locale, preview: $preview, where: { slug: $slug }) {
    items {
      sys {
        id
      }
      internalName
      slug
      postTitle
      postContent {
        json
      }
      featuredImage {
        ...ImaageFragment
      }
      publishedDate
      seo {
        ...SeoFragment
      }
    }
  }
}